#!/bin/bash

function limpaJs() {
    
   for i in $1 ;do 
     if [ ! -d "$i"  ];
       # then rm $i ; fi ;
        then  echo arquivo; 
     else
         limpaJs $i

done

}



for i in js/*.js ;do 
     if [ ! -d "$i"  ];
       # then rm $i ; fi ;
        then  echo arquivo; 
     else
         echo $i/*.js;fi;
          
done
